PREFIX ex: <http://example.org/>

SELECT * WHERE  {
  SERVICE <ex:job> {
    ?s ex:job ?job.
  }

  SERVICE <ex:social> {
    ?s ex:job ?job;
      ex:age ?age ;
      ex:email ?email.
  }
  
  ?s ex:id ?id.
}