PREFIX ex: <http://example.org/>

SELECT * WHERE  {
  SERVICE <http://localhost:3001/sparql> {
    ?s ex:baan ?job.
  }

  SERVICE <http://localhost:3000/sparql> {
    ?s ex:job ?job;
      ex:age ?age ;
      ex:email ?email.
  }
  
  ?s ex:id ?id.
}